name: Run API Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin

      - name: Download and Install Allure CLI
        run: |
          curl -sSL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.23.0/allure-commandline-2.23.0.zip -o allure.zip
          unzip allure.zip
          export PATH=$PATH:./allure-commandline-2.23.0/bin

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Set PATH for Allure CLI
        run: echo "export PATH=$PATH:/path/to/allure/bin" >> $GITHUB_ENV

      - name: Generate Allure Report
        run: allure generate test-results -o allure-report
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
